### ISSUE TITLE
CSGO-Hack Key not found. 

### ISSUE THREAD

**Issue by aethstetic** [DimitriFourny/csgo-hack#1]
Alright So, I'm using your src for making my own hack. But there is 1 mayor thing I don't seem to find. It's the key to open the menu. Whats the default menu open key?

**Comment by DimitriFourny** [comment]
I have used the INSERT key: https://github.com/DimitriFourny/csgo-hack/blob/62eac1cfd23e747313cfa4a9ef917faf94119046/csgo/Hooks.cpp#L217

**Comment by aethstetic** [comment]
Oh yeah thanks!

**Comment by DimitriFourny** [comment]
You are welcome.
